#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate docs/rules.js from skillxray.RULES so the in-browser scanner and
the CLI share ONE source of truth for detection rules.

    python build_web.py            # write docs/rules.js
    python build_web.py --check    # exit 1 if docs/rules.js is stale (CI)

Only the rule *data* is generated. The JS scanning engine (docs/scanner.js)
mirrors the Python engine's logic and is maintained by hand; tests/parity keep
them honest.
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import skillxray  # noqa: E402

OUT = os.path.join(HERE, "docs", "rules.js")

HEADER = ("// GENERATED by build_web.py from skillxray.py — do not edit by hand.\n"
          "// Run `python build_web.py` after changing RULES in skillxray.py.\n")


def render():
    payload = {
        "version": skillxray.__version__,
        "severities": skillxray.SEVERITIES,
        "sevScore": skillxray.SEV_SCORE,
        "rules": skillxray.RULES,
        "urlAllowlist": list(skillxray.URL_ALLOWLIST),
        "officialNames": sorted(skillxray.OFFICIAL_SKILL_NAMES),
    }
    body = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    return HEADER + "window.SKILLXRAY = " + body + ";\n"


def main():
    text = render()
    if "--check" in sys.argv:
        try:
            with io.open(OUT, "r", encoding="utf-8") as f:
                current = f.read()
        except (IOError, OSError):
            current = ""
        if current != text:
            print("docs/rules.js is stale — run `python build_web.py`")
            return 1
        print("docs/rules.js is up to date")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d rules)" % (OUT, len(skillxray.RULES)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
